---

# Note: the order is very important here.  When a zone is added or removed,
# nsd MUST rebuild its database before being restarted.  Otherwise, it will
# fail to start.

- name: rebuild nsd database
  command: "{{ nsd_control_program }} rebuild"
  when: nsd_version == 3

- name: reload nsd database
  command: "{{ nsd_control_program }} reload"

- name: restart nsd
  service: name={{ nsd_service_name }} state=restarted

- name: notify slaves
  command: "{{ nsd_control_program }} notify"
